# Brotli is not bundled into standard NGINX by default; it requires an official open-source module from Google (ngx_brotli). In containerized environments, you usually grab an NGINX image that has it pre-compiled, or build it as a dynamic module.

events{}

http {
    # Turn gzip compression ON
    brotli on;
    brotli_comp_level 4; # Sweet spot for on-the-fly Brotli compression
    brotli_min_length 256;
    brotli_vary on;
    brotli_types
        text/plain
        text/css
        application/json
        application/javascript
        text/xml
        text/javascript;

    server {
        listen 80;
        server_name localhost;

        location / {
            proxy_cache my_sandbox_cache;
            add_header X-Cache-Status $upstream_cache_status;

            proxy_pass http://flask_app_1:5000; # Points to the Flask service name
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}